name: publish-package
on:
  workflow_dispatch:Ë‡
  
jobs:
  compare_versions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Publish package
        run: npm publish
